### ISSUE TITLE
VGVI post-processing: observer must be POLYGON or MULTIPOLYGON

### ISSUE THREAD

**Issue by Jinger1025** [STBrinkmann/protoVS#1]
When I use the code for VGVI post-process, I got the:
Error in sf_to_rast(observer = vgvi_1, v = "VGVI", aoi = observe_sf, max_distance = 400,  : 
  observer must be POLYGON or MULTIPOLYGON

I check the vgvi_1, it is a point shapefile. Do I need to transfer the point to a polygon? another thing is what the aoi means? do you mean the observer?

**Comment by STBrinkmann** [comment]
I just checked the code and saw that I had a small issue when checking the class of the aoi. However, it has no impact on the calculation.

The `observer` parameter describes the observer locations for which you calculated the VGVI. When you want to convert the point layer to a continuous raster, you could use the `st_to_rast()` function.

`aoi` refers to the Area of Interest and describes your study area. It should be a (MULTI) POLYGON, as it describes an area.
If you leave it empty, it will simply take the bounding box from your observations instead.

For further details on the interpolation algorithm behind the `st_to_rast()` function see [here](https://geobrinkmann.com/post/iwd/). 

If you need further help, you could also show me the code and sample data (or the class/structure of your input data).

**Comment by Jinger1025** [comment]
Got it. I should leave the aoi as NULL. I used to assign the observer to it. Now when I mark it as NULL, it works. Thanks a lot for your quick response. By the way, I really appreciate your effort to VGVI, especially the detailed guidance.

**Comment by Jinger1025** [comment]
> I just checked the code and saw that I had a small issue when checking the class of the aoi. However, it has no impact on the calculation.
> 
> The `observer` parameter describes the observer locations for which you calculated the VGVI. When you want to convert the point layer to a continuous raster, you could use the `st_to_rast()` function.
> 
> `aoi` refers to the Area of Interest and describes your study area. It should be a (MULTI) POLYGON, as it describes an area. If you leave it empty, it will simply take the bounding box from your observations instead.
> 
> For further details on the interpolation algorithm behind the `st_to_rast()` function see [here](https://geobrinkmann.com/post/iwd/).
> 
> If you need further help, you could also show me the code and sample data (or the class/structure of your input data).

Got it. I should leave the aoi as NULL. I used to assign the observer to it. Now when I mark it as NULL, it works. Thanks a lot for your quick response. By the way, I really appreciate your effort to VGVI, especially the detailed guidance.

**Comment by STBrinkmann** [comment]
Thanks, glad that you find it useful! Btw. I plan to conduct a complete rework of the GVI package during this winter. Therefore, the protoVS package will be deprecated.
